require("fedesilva.options")
require("fedesilva.packer")
require("fedesilva.map")
require("fedesilva.telescope")
require("fedesilva.cmp")
require("fedesilva.lsp")
require("fedesilva.comment")
require("fedesilva.null-ls")
require("fedesilva.lualine")
require("fedesilva.dashboard")
-- require("fedesilva.rnvimr")
require("nvim-tree").setup()
require('gitsigns').setup()
